<?xml version="1.0" standalone="yes"?>
<!DOCTYPE bookstore
	[
	<!ELEMENT bookstore (book+)>
	<!ELEMENT book (id,title,author)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT author (#PCDATA)>
	]>
<bookstore>
	<book>
		<id>12</id>
		<title>Web Programming</title>
		<author>Bates</author>
	</book>
	<book>
		<id>13</id>
		<title>C programming</title>
		<author>Fourzan</author>
	</book>
</bookstore>